### PR TITLE
moving large sql outside

### PR DESCRIPTION
**Pull request by vitaly-t**
moving SQL into external files, starting with the largest one.

### CODE REVIEW

**Comment by vitaly-t** [comment]
Ahem, strange that Travis says `Unhandled rejection error: schema "pgjson" does not exist`. Any idea why it suddenly cannot see the schema?

**Comment by fiatjaf** [comment]
The only possible issue I could think of is that maybe [this init statement](https://github.com/vitaly-t/pgjson/blob/f1ddc69eb1c8491047a713a86bf98ff0230540f3/sql/init.sql) cannot be executed all at once.

Maybe (I don't remember) there's a reason for [these](https://github.com/fiatjaf/pgjson/blob/master/index.js#L174-L178) to be separated and not all in a single string in the current code.

**Comment by vitaly-t** [comment]
If you execute the entire script locally, it will be successful. That's what confusing. It looks more like some query is executed before the script, i just don't see how.

**Comment by fiatjaf** [comment]
I'm guessing that when you execute it locally the semicolons mean "wait until everything is done" then proceed to the next query, but that isn't the case with the Node driver.

**Comment by vitaly-t** [comment]
I have just tried to move the schema creation to be the guaranteed first step - nothing changed. This is some sort of a mystery. There must be a query executed before we even try to create the schema. Strange.

**Comment by vitaly-t** [comment]
I have found the problem. Your test is invalid, it uses this:

``` js
  beforeEach(function () {
    pj.purgeAll()
    pj.init()
  })
```

you cannot execute asynchronous operations in such manner, as their result becomes unpredictable.

extended log shows that what's hapenning, it first executes `CREATE SCHEMA`, and then `DROP SCHEMA`, then `CREATE TABLE`, which of course breaks :)

**Comment by fiatjaf** [comment]
That may be an error there, but I can't see it. These methods are not asynchronous. Or, in fact, they are, but they are a kind of "fake asynchronous". There's `this.wait` in the back, ensuring that one is called after the other resolves, always.

Also, if this was the case the tests should be broken before, right?

**Pull request closed without merging**
